server:
  port: 7003
spring:
  datasource:
    password: phonebook
    url: jdbc:postgresql://localhost:5432/phonebook
    username: phonebook
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
