server:
  port: 7003
spring:
  datasource:
    password: phonebook
    url: jdbc:postgresql://localhost:5432/phonebook
    username: phonebook
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
phonebook:
  messages:
    succMsg: Contact saved successfuly
    errMSg: Contact failed to save
    succUpdatedMsg: Contact updated successfuly
    deletedSuccMSg: Contact deleted successfuly
    deletedErrMSg: Contact failed to delete